//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReef.Integrations.Agemni.DirecTVAutomation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrder", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SalesOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.BillingAddress BillingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.CustomerContactInfo ContactInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.CreditConsent CreditConsentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.CustomerInfo CustomerInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.EmployeeInfo EmployeeInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.InstallAddress InstallAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.OfferOption OfferOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.ReferralInfo ReferralInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.Agemni.DirecTVAutomation.StoreInfo StoreInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.BillingAddress BillingAddress {
            get {
                return this.BillingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressField, value) != true)) {
                    this.BillingAddressField = value;
                    this.RaisePropertyChanged("BillingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.CustomerContactInfo ContactInfo {
            get {
                return this.ContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfoField, value) != true)) {
                    this.ContactInfoField = value;
                    this.RaisePropertyChanged("ContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.CreditConsent CreditConsent {
            get {
                return this.CreditConsentField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditConsentField, value) != true)) {
                    this.CreditConsentField = value;
                    this.RaisePropertyChanged("CreditConsent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.CustomerInfo CustomerInfo {
            get {
                return this.CustomerInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerInfoField, value) != true)) {
                    this.CustomerInfoField = value;
                    this.RaisePropertyChanged("CustomerInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.EmployeeInfo EmployeeInfo {
            get {
                return this.EmployeeInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeInfoField, value) != true)) {
                    this.EmployeeInfoField = value;
                    this.RaisePropertyChanged("EmployeeInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.InstallAddress InstallAddress {
            get {
                return this.InstallAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallAddressField, value) != true)) {
                    this.InstallAddressField = value;
                    this.RaisePropertyChanged("InstallAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.OfferOption OfferOption {
            get {
                return this.OfferOptionField;
            }
            set {
                if ((this.OfferOptionField.Equals(value) != true)) {
                    this.OfferOptionField = value;
                    this.RaisePropertyChanged("OfferOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.ReferralInfo ReferralInfo {
            get {
                return this.ReferralInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralInfoField, value) != true)) {
                    this.ReferralInfoField = value;
                    this.RaisePropertyChanged("ReferralInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.Agemni.DirecTVAutomation.StoreInfo StoreInfo {
            get {
                return this.StoreInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreInfoField, value) != true)) {
                    this.StoreInfoField = value;
                    this.RaisePropertyChanged("StoreInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingAddress", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class BillingAddress : DataReef.Integrations.Agemni.DirecTVAutomation.AddressInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SameAsInstallAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SameAsInstallAddress {
            get {
                return this.SameAsInstallAddressField;
            }
            set {
                if ((this.SameAsInstallAddressField.Equals(value) != true)) {
                    this.SameAsInstallAddressField = value;
                    this.RaisePropertyChanged("SameAsInstallAddress");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerContactInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CustomerContactInfo : DataReef.Integrations.Agemni.DirecTVAutomation.ContactInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequireSpecialOffersByEmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequireSpecialOffersByEmail {
            get {
                return this.RequireSpecialOffersByEmailField;
            }
            set {
                if ((this.RequireSpecialOffersByEmailField.Equals(value) != true)) {
                    this.RequireSpecialOffersByEmailField = value;
                    this.RaisePropertyChanged("RequireSpecialOffersByEmail");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditConsent", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CreditConsent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowToPerformCreditCheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowToPerformCreditCheck {
            get {
                return this.AllowToPerformCreditCheckField;
            }
            set {
                if ((this.AllowToPerformCreditCheckField.Equals(value) != true)) {
                    this.AllowToPerformCreditCheckField = value;
                    this.RaisePropertyChanged("AllowToPerformCreditCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CustomerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchForExistingCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SearchForExistingCustomer {
            get {
                return this.SearchForExistingCustomerField;
            }
            set {
                if ((this.SearchForExistingCustomerField.Equals(value) != true)) {
                    this.SearchForExistingCustomerField = value;
                    this.RaisePropertyChanged("SearchForExistingCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstallAddress", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InstallAddress : DataReef.Integrations.Agemni.DirecTVAutomation.AddressInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferralInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ReferralInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class StoreInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecTvIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecTvId {
            get {
                return this.DirecTvIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecTvIdField, value) != true)) {
                    this.DirecTvIdField = value;
                    this.RaisePropertyChanged("DirecTvId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreLocation {
            get {
                return this.StoreLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreLocationField, value) != true)) {
                    this.StoreLocationField = value;
                    this.RaisePropertyChanged("StoreLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreName {
            get {
                return this.StoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNameField, value) != true)) {
                    this.StoreNameField = value;
                    this.RaisePropertyChanged("StoreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreNumber {
            get {
                return this.StoreNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNumberField, value) != true)) {
                    this.StoreNumberField = value;
                    this.RaisePropertyChanged("StoreNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferOption", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    public enum OfferOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeasedOption = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchasedOption = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataReef.Integrations.Agemni.DirecTVAutomation.InstallAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataReef.Integrations.Agemni.DirecTVAutomation.BillingAddress))]
    public partial class AddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNo {
            get {
                return this.StreetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNoField, value) != true)) {
                    this.StreetNoField = value;
                    this.RaisePropertyChanged("StreetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber {
            get {
                return this.UnitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitNumberField, value) != true)) {
                    this.UnitNumberField = value;
                    this.RaisePropertyChanged("UnitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactInfo", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DataReef.Integrations.Agemni.DirecTVAutomation.CustomerContactInfo))]
    public partial class ContactInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternatePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverLicenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrivingLicenseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternatePhoneNumber {
            get {
                return this.AlternatePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternatePhoneNumberField, value) != true)) {
                    this.AlternatePhoneNumberField = value;
                    this.RaisePropertyChanged("AlternatePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverLicense {
            get {
                return this.DriverLicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverLicenseField, value) != true)) {
                    this.DriverLicenseField = value;
                    this.RaisePropertyChanged("DriverLicense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DrivingLicenseState {
            get {
                return this.DrivingLicenseStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DrivingLicenseStateField, value) != true)) {
                    this.DrivingLicenseStateField = value;
                    this.RaisePropertyChanged("DrivingLicenseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceSalesOrderResult", Namespace="http://schemas.datacontract.org/2004/07/DtvAutomation.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PlaceSalesOrderResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DirecTVAutomation.IDtvAutomationService")]
    public interface IDtvAutomationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDtvAutomationService/PlaceSalesOrder", ReplyAction="http://tempuri.org/IDtvAutomationService/PlaceSalesOrderResponse")]
        DataReef.Integrations.Agemni.DirecTVAutomation.PlaceSalesOrderResult PlaceSalesOrder(DataReef.Integrations.Agemni.DirecTVAutomation.SalesOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDtvAutomationService/PlaceSalesOrder", ReplyAction="http://tempuri.org/IDtvAutomationService/PlaceSalesOrderResponse")]
        System.Threading.Tasks.Task<DataReef.Integrations.Agemni.DirecTVAutomation.PlaceSalesOrderResult> PlaceSalesOrderAsync(DataReef.Integrations.Agemni.DirecTVAutomation.SalesOrder order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDtvAutomationServiceChannel : DataReef.Integrations.Agemni.DirecTVAutomation.IDtvAutomationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DtvAutomationServiceClient : System.ServiceModel.ClientBase<DataReef.Integrations.Agemni.DirecTVAutomation.IDtvAutomationService>, DataReef.Integrations.Agemni.DirecTVAutomation.IDtvAutomationService {
        
        public DtvAutomationServiceClient() {
        }
        
        public DtvAutomationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DtvAutomationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DtvAutomationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DtvAutomationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataReef.Integrations.Agemni.DirecTVAutomation.PlaceSalesOrderResult PlaceSalesOrder(DataReef.Integrations.Agemni.DirecTVAutomation.SalesOrder order) {
            return base.Channel.PlaceSalesOrder(order);
        }
        
        public System.Threading.Tasks.Task<DataReef.Integrations.Agemni.DirecTVAutomation.PlaceSalesOrderResult> PlaceSalesOrderAsync(DataReef.Integrations.Agemni.DirecTVAutomation.SalesOrder order) {
            return base.Channel.PlaceSalesOrderAsync(order);
        }
    }
}
