CREATE TABLE [dbo].[PrescreensRaw] (
    [ID]                 INT          IDENTITY (1, 1) NOT NULL,
    [First Name]         VARCHAR (50) NULL,
    [Middle Initial]     VARCHAR (50) NULL,
    [Surname]            VARCHAR (50) NULL,
    [Gen Code]           VARCHAR (50) NULL,
    [Street]             VARCHAR (50) NULL,
    [City]               VARCHAR (50) NULL,
    [State Abbreviation] VARCHAR (50) NULL,
    [Zip Code]           VARCHAR (50) NULL,
    [XFC01]              VARCHAR (50) NULL,
    [XFC02]              VARCHAR (50) NULL,
    [XFC03]              VARCHAR (50) NULL,
    [XFC04]              VARCHAR (50) NULL,
    [XFC05]              VARCHAR (50) NULL,
    [XFC06]              VARCHAR (50) NULL,
    [XFC07]              VARCHAR (50) NULL,
    [DEMO7]              VARCHAR (50) NULL,
    [AHI07]              VARCHAR (50) NULL,
    [APR030]             VARCHAR (50) NULL,
    [AHD13]              VARCHAR (50) NULL,
    [DEMO9]              VARCHAR (50) NULL,
    [SCORE1]             VARCHAR (50) NULL,
    [DEM02]              VARCHAR (50) NULL,
    [AAL18]              VARCHAR (50) NULL,
    [AAL19]              VARCHAR (50) NULL,
    [AAL20]              VARCHAR (50) NULL,
    [AAL24]              VARCHAR (50) NULL,
    [AAL25]              VARCHAR (50) NULL,
    [AAL60]              VARCHAR (50) NULL,
    [DRG02]              VARCHAR (50) NULL,
    [AMG08]              VARCHAR (50) NULL,
    [AMG09]              VARCHAR (50) NULL,
    [AMG13]              VARCHAR (50) NULL,
    [AMG14]              VARCHAR (50) NULL,
    [AMG15]              VARCHAR (50) NULL,
    [APRLT24]            VARCHAR (50) NULL,
    CONSTRAINT [PK_PrescreensRaw] PRIMARY KEY CLUSTERED ([ID] ASC)
);

