CREATE TABLE [dbo].[tempFields] (
    [Guid]               UNIQUEIDENTIFIER NOT NULL,
    [DisplayName]        NVARCHAR (100)   NULL,
    [Description]        NVARCHAR (100)   NULL,
    [GroupName]          NVARCHAR (50)    NULL,
    [Value]              NVARCHAR (MAX)   NULL,
    [FormatString]       NVARCHAR (50)    NULL,
    [Id]                 BIGINT           IDENTITY (1, 1) NOT NULL,
    [Name]               NVARCHAR (100)   NULL,
    [Flags]              BIGINT           NULL,
    [TenantID]           INT              NOT NULL,
    [DateCreated]        DATETIME         NOT NULL,
    [DateLastModified]   DATETIME         NULL,
    [CreatedByName]      NVARCHAR (100)   NULL,
    [CreatedByID]        UNIQUEIDENTIFIER NULL,
    [LastModifiedBy]     UNIQUEIDENTIFIER NULL,
    [LastModifiedByName] NVARCHAR (100)   NULL,
    [Version]            INT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    [ExternalID]         NVARCHAR (50)    NULL,
    [TagString]          NVARCHAR (1000)  NULL,
    [OccupantId]         UNIQUEIDENTIFIER NULL,
    [PropertyId]         UNIQUEIDENTIFIER NULL
);

