CREATE PROCEDURE proc_OUSettings
	@OUID UNIQUEIDENTIFIER
AS
BEGIN

-- EXEC proc_OUSettings 'BBD36C5E-DDDA-4133-90AB-E3D70981B5C4'

SELECT S.*
FROM OUSettings S
INNER JOIN 
(
	SELECT T.Guid, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) as Level
	from OUTreeUP(@OUID) T
) T
ON S.OUID = T.Guid
WHERE S.IsDeleted = 0
ORDER BY Level DESC

END