//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReef.Integrations.RedBell.RedBell {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderRequest", Namespace="http://schemas.redbellre.com/services")]
    [System.SerializableAttribute()]
    public partial class OrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.RedBell.RedBell.CustomDataList CustomDataListField;
        
        private string LoanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.RedBell.RedBell.MonthsBack MonthsBackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoolNameField;
        
        private DataReef.Integrations.RedBell.RedBell.ProductCode ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.RedBell.RedBell.PropertyType PropertyTypeField;
        
        private string StateField;
        
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.RedBell.RedBell.CustomDataList CustomDataList {
            get {
                return this.CustomDataListField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDataListField, value) != true)) {
                    this.CustomDataListField = value;
                    this.RaisePropertyChanged("CustomDataList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string LoanNum {
            get {
                return this.LoanNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanNumField, value) != true)) {
                    this.LoanNumField = value;
                    this.RaisePropertyChanged("LoanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.RedBell.RedBell.MonthsBack MonthsBack {
            get {
                return this.MonthsBackField;
            }
            set {
                if ((this.MonthsBackField.Equals(value) != true)) {
                    this.MonthsBackField = value;
                    this.RaisePropertyChanged("MonthsBack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoolName {
            get {
                return this.PoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolNameField, value) != true)) {
                    this.PoolNameField = value;
                    this.RaisePropertyChanged("PoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DataReef.Integrations.RedBell.RedBell.ProductCode ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((this.ProductCodeField.Equals(value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.RedBell.RedBell.PropertyType PropertyType {
            get {
                return this.PropertyTypeField;
            }
            set {
                if ((this.PropertyTypeField.Equals(value) != true)) {
                    this.PropertyTypeField = value;
                    this.RaisePropertyChanged("PropertyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CustomDataList", Namespace="http://schemas.redbellre.com/services", ItemName="CustomData", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class CustomDataList : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthsBack", Namespace="http://schemas.redbellre.com/services")]
    public enum MonthsBack : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Three = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Six = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twelve = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCode", Namespace="http://schemas.redbellre.com/services")]
    public enum ProductCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ave = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avm = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyType", Namespace="http://schemas.redbellre.com/services")]
    public enum PropertyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SingleFamily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiFamily = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Condo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileManufactured = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.redbellre.com/services")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RbOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataReef.Integrations.RedBell.RedBell.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RbOrderId {
            get {
                return this.RbOrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RbOrderIdField, value) != true)) {
                    this.RbOrderIdField = value;
                    this.RaisePropertyChanged("RbOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnData {
            get {
                return this.ReturnDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDataField, value) != true)) {
                    this.ReturnDataField = value;
                    this.RaisePropertyChanged("ReturnData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataReef.Integrations.RedBell.RedBell.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.redbellre.com/services")]
    public enum ResponseStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.redbellre.com/services", ConfigurationName="RedBell.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.redbellre.com/services/IOrderService/Upload", ReplyAction="http://schemas.redbellre.com/services/IOrderService/UploadResponse")]
        DataReef.Integrations.RedBell.RedBell.Response Upload(DataReef.Integrations.RedBell.RedBell.OrderRequest order, bool returnOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.redbellre.com/services/IOrderService/Upload", ReplyAction="http://schemas.redbellre.com/services/IOrderService/UploadResponse")]
        System.Threading.Tasks.Task<DataReef.Integrations.RedBell.RedBell.Response> UploadAsync(DataReef.Integrations.RedBell.RedBell.OrderRequest order, bool returnOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.redbellre.com/services/IOrderService/UploadSync", ReplyAction="http://schemas.redbellre.com/services/IOrderService/UploadSyncResponse")]
        DataReef.Integrations.RedBell.RedBell.Response UploadSync(DataReef.Integrations.RedBell.RedBell.OrderRequest order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.redbellre.com/services/IOrderService/UploadSync", ReplyAction="http://schemas.redbellre.com/services/IOrderService/UploadSyncResponse")]
        System.Threading.Tasks.Task<DataReef.Integrations.RedBell.RedBell.Response> UploadSyncAsync(DataReef.Integrations.RedBell.RedBell.OrderRequest order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : DataReef.Integrations.RedBell.RedBell.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<DataReef.Integrations.RedBell.RedBell.IOrderService>, DataReef.Integrations.RedBell.RedBell.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataReef.Integrations.RedBell.RedBell.Response Upload(DataReef.Integrations.RedBell.RedBell.OrderRequest order, bool returnOrderId) {
            return base.Channel.Upload(order, returnOrderId);
        }
        
        public System.Threading.Tasks.Task<DataReef.Integrations.RedBell.RedBell.Response> UploadAsync(DataReef.Integrations.RedBell.RedBell.OrderRequest order, bool returnOrderId) {
            return base.Channel.UploadAsync(order, returnOrderId);
        }
        
        public DataReef.Integrations.RedBell.RedBell.Response UploadSync(DataReef.Integrations.RedBell.RedBell.OrderRequest order) {
            return base.Channel.UploadSync(order);
        }
        
        public System.Threading.Tasks.Task<DataReef.Integrations.RedBell.RedBell.Response> UploadSyncAsync(DataReef.Integrations.RedBell.RedBell.OrderRequest order) {
            return base.Channel.UploadSyncAsync(order);
        }
    }
}
