// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Merging_PPA_and_Loan_Contracts_enum_Values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merging_PPA_and_Loan_Contracts_enum_Values));
        
        string IMigrationMetadata.Id
        {
            get { return "201608220920307_Merging_PPA_and_Loan_Contracts_enum_Values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
