// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StoredProcs_For_Webhooks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoredProcs_For_Webhooks));
        
        string IMigrationMetadata.Id
        {
            get { return "201611022252551_StoredProcs_For_Webhooks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
