// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Increasing_precision_for_Obstruction_Points : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Increasing_precision_for_Obstruction_Points));
        
        string IMigrationMetadata.Id
        {
            get { return "201702071002461_Increasing_precision_for_Obstruction_Points"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
