// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seeding_internalAPI_credentials_and_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seeding_internalAPI_credentials_and_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201702200915557_Seeding_internalAPI_credentials_and_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
