// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Leaving_Only_one_generic_mortgage_finance_plan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Leaving_Only_one_generic_mortgage_finance_plan));
        
        string IMigrationMetadata.Id
        {
            get { return "201703061752468_Leaving_Only_one_generic_mortgage_finance_plan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
