// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Setting_FinancePlanDetails_FinanceOptionID_and_DealerFee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setting_FinancePlanDetails_FinanceOptionID_and_DealerFee));
        
        string IMigrationMetadata.Id
        {
            get { return "201702241127503_Setting_FinancePlanDetails_FinanceOptionID_and_DealerFee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
