// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updating_proc_TerritoryAnalytics_storedProceduresql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updating_proc_TerritoryAnalytics_storedProceduresql));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231036141_Updating_proc_TerritoryAnalytics_storedProcedure.sql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
