// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdderItem_MakeHistoryFieldsNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdderItem_MakeHistoryFieldsNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241115092_AdderItem_MakeHistoryFieldsNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
