// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removing_FinancePlan_Unused_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removing_FinancePlan_Unused_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141827163_Removing_FinancePlan_Unused_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
