// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednavigationpropertiesonappointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednavigationpropertiesonappointment));
        
        string IMigrationMetadata.Id
        {
            get { return "201902131328296_Added navigation properties on appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
