// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedOnlineAppointmentField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedOnlineAppointmentField));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171057175_Added OnlineAppointment Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
