// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedOnlineAppointmentParaFieldinPeople : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedOnlineAppointmentParaFieldinPeople));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171047087_Added OnlineAppointmentPara Field in People"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
