// <auto-generated />
namespace DataReef.TM.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Lenderfee_and_PPW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Lenderfee_and_PPW));
        
        string IMigrationMetadata.Id
        {
            get { return "202008181730517_added_Lenderfee_and_PPW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
