//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DataReef.Integrations.Agemni.com.agemni.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/AgemniWebService/Service1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getExeptionReportObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountIDFromLeadIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountIDFromPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeadIDFromPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadProviderDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCampaignNameFromLeadIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCampaignNameFromAccountIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProviderFromLeadIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProviderFromAccountIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::DataReef.Integrations.Agemni.Properties.Settings.Default.DataReef_Integrations_Agemni_com_agemni_www_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getExeptionReportObjectCompletedEventHandler getExeptionReportObjectCompleted;
        
        /// <remarks/>
        public event ValidateEntityCompletedEventHandler ValidateEntityCompleted;
        
        /// <remarks/>
        public event getTypesCompletedEventHandler getTypesCompleted;
        
        /// <remarks/>
        public event GetAccountIDFromLeadIDCompletedEventHandler GetAccountIDFromLeadIDCompleted;
        
        /// <remarks/>
        public event GetAccountIDFromPhoneCompletedEventHandler GetAccountIDFromPhoneCompleted;
        
        /// <remarks/>
        public event GetLeadIDFromPhoneCompletedEventHandler GetLeadIDFromPhoneCompleted;
        
        /// <remarks/>
        public event CreateEntityCompletedEventHandler CreateEntityCompleted;
        
        /// <remarks/>
        public event UploadProviderDocumentCompletedEventHandler UploadProviderDocumentCompleted;
        
        /// <remarks/>
        public event UpdateEntityCompletedEventHandler UpdateEntityCompleted;
        
        /// <remarks/>
        public event getCampaignNameFromLeadIDCompletedEventHandler getCampaignNameFromLeadIDCompleted;
        
        /// <remarks/>
        public event getCampaignNameFromAccountIDCompletedEventHandler getCampaignNameFromAccountIDCompleted;
        
        /// <remarks/>
        public event getProviderFromLeadIDCompletedEventHandler getProviderFromLeadIDCompleted;
        
        /// <remarks/>
        public event getProviderFromAccountIDCompletedEventHandler getProviderFromAccountIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getExeptionReportObject", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionReport getExeptionReportObject() {
            object[] results = this.Invoke("getExeptionReportObject", new object[0]);
            return ((ExceptionReport)(results[0]));
        }
        
        /// <remarks/>
        public void getExeptionReportObjectAsync() {
            this.getExeptionReportObjectAsync(null);
        }
        
        /// <remarks/>
        public void getExeptionReportObjectAsync(object userState) {
            if ((this.getExeptionReportObjectOperationCompleted == null)) {
                this.getExeptionReportObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExeptionReportObjectOperationCompleted);
            }
            this.InvokeAsync("getExeptionReportObject", new object[0], this.getExeptionReportObjectOperationCompleted, userState);
        }
        
        private void OngetExeptionReportObjectOperationCompleted(object arg) {
            if ((this.getExeptionReportObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExeptionReportObjectCompleted(this, new getExeptionReportObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/ValidateEntity", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object ValidateEntity(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            object[] results = this.Invoke("ValidateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            this.ValidateEntityAsync(strUsername, strPassword, strCompanyName, objecttype, keys, values, null);
        }
        
        /// <remarks/>
        public void ValidateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values, object userState) {
            if ((this.ValidateEntityOperationCompleted == null)) {
                this.ValidateEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEntityOperationCompleted);
            }
            this.InvokeAsync("ValidateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values}, this.ValidateEntityOperationCompleted, userState);
        }
        
        private void OnValidateEntityOperationCompleted(object arg) {
            if ((this.ValidateEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEntityCompleted(this, new ValidateEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getTypes", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Types getTypes() {
            object[] results = this.Invoke("getTypes", new object[0]);
            return ((Types)(results[0]));
        }
        
        /// <remarks/>
        public void getTypesAsync() {
            this.getTypesAsync(null);
        }
        
        /// <remarks/>
        public void getTypesAsync(object userState) {
            if ((this.getTypesOperationCompleted == null)) {
                this.getTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTypesOperationCompleted);
            }
            this.InvokeAsync("getTypes", new object[0], this.getTypesOperationCompleted, userState);
        }
        
        private void OngetTypesOperationCompleted(object arg) {
            if ((this.getTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTypesCompleted(this, new getTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/GetAccountIDFromLeadID", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountIDFromLeadID(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            object[] results = this.Invoke("GetAccountIDFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountIDFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            this.GetAccountIDFromLeadIDAsync(strUsername, strPassword, strCompanyName, LeadID, null);
        }
        
        /// <remarks/>
        public void GetAccountIDFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID, object userState) {
            if ((this.GetAccountIDFromLeadIDOperationCompleted == null)) {
                this.GetAccountIDFromLeadIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountIDFromLeadIDOperationCompleted);
            }
            this.InvokeAsync("GetAccountIDFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID}, this.GetAccountIDFromLeadIDOperationCompleted, userState);
        }
        
        private void OnGetAccountIDFromLeadIDOperationCompleted(object arg) {
            if ((this.GetAccountIDFromLeadIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountIDFromLeadIDCompleted(this, new GetAccountIDFromLeadIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/GetAccountIDFromPhone", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountIDFromPhone(string strUsername, string strPassword, string strCompanyName, string Phone) {
            object[] results = this.Invoke("GetAccountIDFromPhone", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        Phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountIDFromPhoneAsync(string strUsername, string strPassword, string strCompanyName, string Phone) {
            this.GetAccountIDFromPhoneAsync(strUsername, strPassword, strCompanyName, Phone, null);
        }
        
        /// <remarks/>
        public void GetAccountIDFromPhoneAsync(string strUsername, string strPassword, string strCompanyName, string Phone, object userState) {
            if ((this.GetAccountIDFromPhoneOperationCompleted == null)) {
                this.GetAccountIDFromPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountIDFromPhoneOperationCompleted);
            }
            this.InvokeAsync("GetAccountIDFromPhone", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        Phone}, this.GetAccountIDFromPhoneOperationCompleted, userState);
        }
        
        private void OnGetAccountIDFromPhoneOperationCompleted(object arg) {
            if ((this.GetAccountIDFromPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountIDFromPhoneCompleted(this, new GetAccountIDFromPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/GetLeadIDFromPhone", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLeadIDFromPhone(string strUsername, string strPassword, string strCompanyName, string Phone) {
            object[] results = this.Invoke("GetLeadIDFromPhone", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        Phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLeadIDFromPhoneAsync(string strUsername, string strPassword, string strCompanyName, string Phone) {
            this.GetLeadIDFromPhoneAsync(strUsername, strPassword, strCompanyName, Phone, null);
        }
        
        /// <remarks/>
        public void GetLeadIDFromPhoneAsync(string strUsername, string strPassword, string strCompanyName, string Phone, object userState) {
            if ((this.GetLeadIDFromPhoneOperationCompleted == null)) {
                this.GetLeadIDFromPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeadIDFromPhoneOperationCompleted);
            }
            this.InvokeAsync("GetLeadIDFromPhone", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        Phone}, this.GetLeadIDFromPhoneOperationCompleted, userState);
        }
        
        private void OnGetLeadIDFromPhoneOperationCompleted(object arg) {
            if ((this.GetLeadIDFromPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeadIDFromPhoneCompleted(this, new GetLeadIDFromPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/CreateEntity", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object CreateEntity(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            object[] results = this.Invoke("CreateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void CreateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            this.CreateEntityAsync(strUsername, strPassword, strCompanyName, objecttype, keys, values, null);
        }
        
        /// <remarks/>
        public void CreateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values, object userState) {
            if ((this.CreateEntityOperationCompleted == null)) {
                this.CreateEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEntityOperationCompleted);
            }
            this.InvokeAsync("CreateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values}, this.CreateEntityOperationCompleted, userState);
        }
        
        private void OnCreateEntityOperationCompleted(object arg) {
            if ((this.CreateEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEntityCompleted(this, new CreateEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/UploadProviderDocument", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object UploadProviderDocument(string strUsername, string strPassword, string strCompanyName, string strProvider, string strClaimId, string strAccountNumber, string strDoc, string strEmployeeId) {
            object[] results = this.Invoke("UploadProviderDocument", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        strProvider,
                        strClaimId,
                        strAccountNumber,
                        strDoc,
                        strEmployeeId});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void UploadProviderDocumentAsync(string strUsername, string strPassword, string strCompanyName, string strProvider, string strClaimId, string strAccountNumber, string strDoc, string strEmployeeId) {
            this.UploadProviderDocumentAsync(strUsername, strPassword, strCompanyName, strProvider, strClaimId, strAccountNumber, strDoc, strEmployeeId, null);
        }
        
        /// <remarks/>
        public void UploadProviderDocumentAsync(string strUsername, string strPassword, string strCompanyName, string strProvider, string strClaimId, string strAccountNumber, string strDoc, string strEmployeeId, object userState) {
            if ((this.UploadProviderDocumentOperationCompleted == null)) {
                this.UploadProviderDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadProviderDocumentOperationCompleted);
            }
            this.InvokeAsync("UploadProviderDocument", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        strProvider,
                        strClaimId,
                        strAccountNumber,
                        strDoc,
                        strEmployeeId}, this.UploadProviderDocumentOperationCompleted, userState);
        }
        
        private void OnUploadProviderDocumentOperationCompleted(object arg) {
            if ((this.UploadProviderDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadProviderDocumentCompleted(this, new UploadProviderDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/UpdateEntity", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object UpdateEntity(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            object[] results = this.Invoke("UpdateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values) {
            this.UpdateEntityAsync(strUsername, strPassword, strCompanyName, objecttype, keys, values, null);
        }
        
        /// <remarks/>
        public void UpdateEntityAsync(string strUsername, string strPassword, string strCompanyName, int objecttype, object[] keys, object[] values, object userState) {
            if ((this.UpdateEntityOperationCompleted == null)) {
                this.UpdateEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEntityOperationCompleted);
            }
            this.InvokeAsync("UpdateEntity", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        objecttype,
                        keys,
                        values}, this.UpdateEntityOperationCompleted, userState);
        }
        
        private void OnUpdateEntityOperationCompleted(object arg) {
            if ((this.UpdateEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEntityCompleted(this, new UpdateEntityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getCampaignNameFromLeadID", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object getCampaignNameFromLeadID(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            object[] results = this.Invoke("getCampaignNameFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getCampaignNameFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            this.getCampaignNameFromLeadIDAsync(strUsername, strPassword, strCompanyName, LeadID, null);
        }
        
        /// <remarks/>
        public void getCampaignNameFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID, object userState) {
            if ((this.getCampaignNameFromLeadIDOperationCompleted == null)) {
                this.getCampaignNameFromLeadIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCampaignNameFromLeadIDOperationCompleted);
            }
            this.InvokeAsync("getCampaignNameFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID}, this.getCampaignNameFromLeadIDOperationCompleted, userState);
        }
        
        private void OngetCampaignNameFromLeadIDOperationCompleted(object arg) {
            if ((this.getCampaignNameFromLeadIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCampaignNameFromLeadIDCompleted(this, new getCampaignNameFromLeadIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getCampaignNameFromAccountID", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object getCampaignNameFromAccountID(string strUsername, string strPassword, string strCompanyName, string AccountID) {
            object[] results = this.Invoke("getCampaignNameFromAccountID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        AccountID});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getCampaignNameFromAccountIDAsync(string strUsername, string strPassword, string strCompanyName, string AccountID) {
            this.getCampaignNameFromAccountIDAsync(strUsername, strPassword, strCompanyName, AccountID, null);
        }
        
        /// <remarks/>
        public void getCampaignNameFromAccountIDAsync(string strUsername, string strPassword, string strCompanyName, string AccountID, object userState) {
            if ((this.getCampaignNameFromAccountIDOperationCompleted == null)) {
                this.getCampaignNameFromAccountIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCampaignNameFromAccountIDOperationCompleted);
            }
            this.InvokeAsync("getCampaignNameFromAccountID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        AccountID}, this.getCampaignNameFromAccountIDOperationCompleted, userState);
        }
        
        private void OngetCampaignNameFromAccountIDOperationCompleted(object arg) {
            if ((this.getCampaignNameFromAccountIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCampaignNameFromAccountIDCompleted(this, new getCampaignNameFromAccountIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getProviderFromLeadID", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object getProviderFromLeadID(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            object[] results = this.Invoke("getProviderFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getProviderFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID) {
            this.getProviderFromLeadIDAsync(strUsername, strPassword, strCompanyName, LeadID, null);
        }
        
        /// <remarks/>
        public void getProviderFromLeadIDAsync(string strUsername, string strPassword, string strCompanyName, string LeadID, object userState) {
            if ((this.getProviderFromLeadIDOperationCompleted == null)) {
                this.getProviderFromLeadIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProviderFromLeadIDOperationCompleted);
            }
            this.InvokeAsync("getProviderFromLeadID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        LeadID}, this.getProviderFromLeadIDOperationCompleted, userState);
        }
        
        private void OngetProviderFromLeadIDOperationCompleted(object arg) {
            if ((this.getProviderFromLeadIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProviderFromLeadIDCompleted(this, new getProviderFromLeadIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgemniWebService/Service1/getProviderFromAccountID", RequestNamespace="http://tempuri.org/AgemniWebService/Service1", ResponseNamespace="http://tempuri.org/AgemniWebService/Service1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object getProviderFromAccountID(string strUsername, string strPassword, string strCompanyName, string AccountID) {
            object[] results = this.Invoke("getProviderFromAccountID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        AccountID});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getProviderFromAccountIDAsync(string strUsername, string strPassword, string strCompanyName, string AccountID) {
            this.getProviderFromAccountIDAsync(strUsername, strPassword, strCompanyName, AccountID, null);
        }
        
        /// <remarks/>
        public void getProviderFromAccountIDAsync(string strUsername, string strPassword, string strCompanyName, string AccountID, object userState) {
            if ((this.getProviderFromAccountIDOperationCompleted == null)) {
                this.getProviderFromAccountIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProviderFromAccountIDOperationCompleted);
            }
            this.InvokeAsync("getProviderFromAccountID", new object[] {
                        strUsername,
                        strPassword,
                        strCompanyName,
                        AccountID}, this.getProviderFromAccountIDOperationCompleted, userState);
        }
        
        private void OngetProviderFromAccountIDOperationCompleted(object arg) {
            if ((this.getProviderFromAccountIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProviderFromAccountIDCompleted(this, new getProviderFromAccountIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AgemniWebService/Service1")]
    public partial class ExceptionReport {
        
        private statusCodes statusCodeField;
        
        private string statusField;
        
        private string descriptionField;
        
        private int errorNumberField;
        
        private string xmlResultField;
        
        private bool entityValidatedField;
        
        private bool entityCreatedField;
        
        private bool entityUpdatedField;
        
        private int entityIDCreatedField;
        
        private bool isloggedInField;
        
        /// <remarks/>
        public statusCodes statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int errorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string xmlResult {
            get {
                return this.xmlResultField;
            }
            set {
                this.xmlResultField = value;
            }
        }
        
        /// <remarks/>
        public bool EntityValidated {
            get {
                return this.entityValidatedField;
            }
            set {
                this.entityValidatedField = value;
            }
        }
        
        /// <remarks/>
        public bool EntityCreated {
            get {
                return this.entityCreatedField;
            }
            set {
                this.entityCreatedField = value;
            }
        }
        
        /// <remarks/>
        public bool EntityUpdated {
            get {
                return this.entityUpdatedField;
            }
            set {
                this.entityUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public int EntityIDCreated {
            get {
                return this.entityIDCreatedField;
            }
            set {
                this.entityIDCreatedField = value;
            }
        }
        
        /// <remarks/>
        public bool isloggedIn {
            get {
                return this.isloggedInField;
            }
            set {
                this.isloggedInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AgemniWebService/Service1")]
    public enum statusCodes {
        
        /// <remarks/>
        Succeeded,
        
        /// <remarks/>
        CompanyNameNotIdentified,
        
        /// <remarks/>
        CouldNotFindSpecificServer,
        
        /// <remarks/>
        CouldNotConnectToInternal,
        
        /// <remarks/>
        InvalidUsernamePassword,
        
        /// <remarks/>
        ProblemDuringPasswordValidation,
        
        /// <remarks/>
        EntityAlreadyExists,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/AgemniWebService/Service1")]
    public partial class Types {
        
        private int entity_Account_TypeField;
        
        private int entity_Lead_TypeField;
        
        private int entity_Invoice_TypeField;
        
        private int entity_Appointment_TypeField;
        
        private int entity_Note_TypeField;
        
        private int entity_CreditCard_TypeField;
        
        private int entity_ACH_TypeField;
        
        private int entity_Payroll_TypeField;
        
        private int entity_TechArriveDepart_TypeField;
        
        private int entity_Employee_TypeField;
        
        private string invoice_Type_ACField;
        
        private string invoice_Type_CHField;
        
        private string invoice_Type_TCField;
        
        private string invoice_SatelliteProvider_DIRECTVField;
        
        private string invoice_SatelliteProvider_DISHField;
        
        private string invoice_SatelliteProvider_SAIField;
        
        private string invoice_SatelliteProvider_HUGHESNETField;
        
        private string invoice_SatelliteProvider_AccellerField;
        
        private string invoice_SatelliteProvider_MonitronicsField;
        
        private string invoice_SatelliteProvider_VectorField;
        
        private string invoice_SatelliteProvider_CounterforceField;
        
        private string invoice_SatelliteProvider_SirenField;
        
        private string invoice_SatelliteProvider_ADTField;
        
        private string invoice_SatelliteProvider_BrinksField;
        
        private string invoice_SatelliteProvider_Security_NetworksField;
        
        private string invoice_SatelliteProvider_AlltelField;
        
        private string invoice_SatelliteProvider_ATTField;
        
        private string invoice_SatelliteProvider_Qwest_BroadbandField;
        
        private string invoice_SatelliteProvider_CingularField;
        
        private string invoice_SatelliteProvider_ClearWireField;
        
        private string invoice_SatelliteProvider_Comcast_BroadbandField;
        
        private string invoice_SatelliteProvider_Comcast_TVField;
        
        private string invoice_SatelliteProvider_CricketField;
        
        private string invoice_SatelliteProvider_DISH_NetworkField;
        
        private string invoice_SatelliteProvider_DISH_CommercialField;
        
        private string invoice_SatelliteProvider_DSI_FulfillmentField;
        
        private string invoice_SatelliteProvider_DIRECTV_CommercialField;
        
        private string invoice_SatelliteProvider_EarthLinkField;
        
        private string invoice_SatelliteProvider_WorldTVField;
        
        private string invoice_SatelliteProvider_HSP_FulfillmentField;
        
        private string invoice_SatelliteProvider_HughesNet_FulfillmentField;
        
        private string invoice_SatelliteProvider_NextelField;
        
        private string invoice_SatelliteProvider_Perfect_10_FulfillmentField;
        
        private string invoice_SatelliteProvider_QwestField;
        
        private string invoice_SatelliteProvider_Qwest_WirelessField;
        
        private string invoice_SatelliteProvider_SIRIUSField;
        
        private string invoice_SatelliteProvider_Sky_AngelField;
        
        private string invoice_SatelliteProvider_SprintField;
        
        private string invoice_SatelliteProvider_SunComField;
        
        private string invoice_SatelliteProvider_TMobileField;
        
        private string invoice_SatelliteProvider_US_DTVField;
        
        private string invoice_SatelliteProvider_VerizonField;
        
        private string invoice_SatelliteProvider_VonageField;
        
        private string invoice_SatelliteProvider_WildBlueField;
        
        private string invoice_SatelliteProvider_WildBlue_FulfillmentField;
        
        private string invoice_SatelliteProvider_XM_RadioField;
        
        private string invoice_Status_PendingField;
        
        private string invoice_Status_CompletedField;
        
        private string invoice_Status_CancelledField;
        
        private string invoice_Status_NotScheduledField;
        
        private string invoice_Status_ChargebackField;
        
        private string appointment_Results_OpenField;
        
        private string appointment_Results_RescheduledField;
        
        private string appointment_Results_CompletedField;
        
        private string appointment_Results_CancelledField;
        
        private string appointment_Results_ClosedField;
        
        private string creditCard_Type_VisaField;
        
        private string creditCard_Type_MastercardField;
        
        private string creditCard_Type_AmericanExpressField;
        
        private string creditCard_Type_DiscoverField;
        
        private string note_Type_AccountingField;
        
        private string note_Type_TicketField;
        
        private string note_Type_ComplaintField;
        
        private string note_Type_Follow_up_2Field;
        
        private string note_Type_ProcessingField;
        
        private string note_Type_Follow_up_3Field;
        
        private string note_Type_ReconciliationField;
        
        private string note_Type_Lead_FlowField;
        
        private string note_Type_Manual_UpdateField;
        
        private string note_Type_RouteField;
        
        private string note_Type_Pre_CallField;
        
        private string note_Type_Follow_up_1Field;
        
        private string note_Type_StatusField;
        
        private string note_Type_Trouble_CallField;
        
        private string note_Type_CallbackField;
        
        private string note_Type_BillingField;
        
        /// <remarks/>
        public int Entity_Account_Type {
            get {
                return this.entity_Account_TypeField;
            }
            set {
                this.entity_Account_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Lead_Type {
            get {
                return this.entity_Lead_TypeField;
            }
            set {
                this.entity_Lead_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Invoice_Type {
            get {
                return this.entity_Invoice_TypeField;
            }
            set {
                this.entity_Invoice_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Appointment_Type {
            get {
                return this.entity_Appointment_TypeField;
            }
            set {
                this.entity_Appointment_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Note_Type {
            get {
                return this.entity_Note_TypeField;
            }
            set {
                this.entity_Note_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_CreditCard_Type {
            get {
                return this.entity_CreditCard_TypeField;
            }
            set {
                this.entity_CreditCard_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_ACH_Type {
            get {
                return this.entity_ACH_TypeField;
            }
            set {
                this.entity_ACH_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Payroll_Type {
            get {
                return this.entity_Payroll_TypeField;
            }
            set {
                this.entity_Payroll_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_TechArriveDepart_Type {
            get {
                return this.entity_TechArriveDepart_TypeField;
            }
            set {
                this.entity_TechArriveDepart_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Entity_Employee_Type {
            get {
                return this.entity_Employee_TypeField;
            }
            set {
                this.entity_Employee_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Type_AC {
            get {
                return this.invoice_Type_ACField;
            }
            set {
                this.invoice_Type_ACField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Type_CH {
            get {
                return this.invoice_Type_CHField;
            }
            set {
                this.invoice_Type_CHField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Type_TC {
            get {
                return this.invoice_Type_TCField;
            }
            set {
                this.invoice_Type_TCField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DIRECTV {
            get {
                return this.invoice_SatelliteProvider_DIRECTVField;
            }
            set {
                this.invoice_SatelliteProvider_DIRECTVField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DISH {
            get {
                return this.invoice_SatelliteProvider_DISHField;
            }
            set {
                this.invoice_SatelliteProvider_DISHField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_SAI {
            get {
                return this.invoice_SatelliteProvider_SAIField;
            }
            set {
                this.invoice_SatelliteProvider_SAIField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_HUGHESNET {
            get {
                return this.invoice_SatelliteProvider_HUGHESNETField;
            }
            set {
                this.invoice_SatelliteProvider_HUGHESNETField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Acceller {
            get {
                return this.invoice_SatelliteProvider_AccellerField;
            }
            set {
                this.invoice_SatelliteProvider_AccellerField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Monitronics {
            get {
                return this.invoice_SatelliteProvider_MonitronicsField;
            }
            set {
                this.invoice_SatelliteProvider_MonitronicsField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Vector {
            get {
                return this.invoice_SatelliteProvider_VectorField;
            }
            set {
                this.invoice_SatelliteProvider_VectorField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Counterforce {
            get {
                return this.invoice_SatelliteProvider_CounterforceField;
            }
            set {
                this.invoice_SatelliteProvider_CounterforceField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Siren {
            get {
                return this.invoice_SatelliteProvider_SirenField;
            }
            set {
                this.invoice_SatelliteProvider_SirenField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_ADT {
            get {
                return this.invoice_SatelliteProvider_ADTField;
            }
            set {
                this.invoice_SatelliteProvider_ADTField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Brinks {
            get {
                return this.invoice_SatelliteProvider_BrinksField;
            }
            set {
                this.invoice_SatelliteProvider_BrinksField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Security_Networks {
            get {
                return this.invoice_SatelliteProvider_Security_NetworksField;
            }
            set {
                this.invoice_SatelliteProvider_Security_NetworksField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Alltel {
            get {
                return this.invoice_SatelliteProvider_AlltelField;
            }
            set {
                this.invoice_SatelliteProvider_AlltelField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_ATT {
            get {
                return this.invoice_SatelliteProvider_ATTField;
            }
            set {
                this.invoice_SatelliteProvider_ATTField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Qwest_Broadband {
            get {
                return this.invoice_SatelliteProvider_Qwest_BroadbandField;
            }
            set {
                this.invoice_SatelliteProvider_Qwest_BroadbandField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Cingular {
            get {
                return this.invoice_SatelliteProvider_CingularField;
            }
            set {
                this.invoice_SatelliteProvider_CingularField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_ClearWire {
            get {
                return this.invoice_SatelliteProvider_ClearWireField;
            }
            set {
                this.invoice_SatelliteProvider_ClearWireField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Comcast_Broadband {
            get {
                return this.invoice_SatelliteProvider_Comcast_BroadbandField;
            }
            set {
                this.invoice_SatelliteProvider_Comcast_BroadbandField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Comcast_TV {
            get {
                return this.invoice_SatelliteProvider_Comcast_TVField;
            }
            set {
                this.invoice_SatelliteProvider_Comcast_TVField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Cricket {
            get {
                return this.invoice_SatelliteProvider_CricketField;
            }
            set {
                this.invoice_SatelliteProvider_CricketField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DISH_Network {
            get {
                return this.invoice_SatelliteProvider_DISH_NetworkField;
            }
            set {
                this.invoice_SatelliteProvider_DISH_NetworkField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DISH_Commercial {
            get {
                return this.invoice_SatelliteProvider_DISH_CommercialField;
            }
            set {
                this.invoice_SatelliteProvider_DISH_CommercialField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DSI_Fulfillment {
            get {
                return this.invoice_SatelliteProvider_DSI_FulfillmentField;
            }
            set {
                this.invoice_SatelliteProvider_DSI_FulfillmentField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_DIRECTV_Commercial {
            get {
                return this.invoice_SatelliteProvider_DIRECTV_CommercialField;
            }
            set {
                this.invoice_SatelliteProvider_DIRECTV_CommercialField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_EarthLink {
            get {
                return this.invoice_SatelliteProvider_EarthLinkField;
            }
            set {
                this.invoice_SatelliteProvider_EarthLinkField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_WorldTV {
            get {
                return this.invoice_SatelliteProvider_WorldTVField;
            }
            set {
                this.invoice_SatelliteProvider_WorldTVField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_HSP_Fulfillment {
            get {
                return this.invoice_SatelliteProvider_HSP_FulfillmentField;
            }
            set {
                this.invoice_SatelliteProvider_HSP_FulfillmentField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_HughesNet_Fulfillment {
            get {
                return this.invoice_SatelliteProvider_HughesNet_FulfillmentField;
            }
            set {
                this.invoice_SatelliteProvider_HughesNet_FulfillmentField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Nextel {
            get {
                return this.invoice_SatelliteProvider_NextelField;
            }
            set {
                this.invoice_SatelliteProvider_NextelField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Perfect_10_Fulfillment {
            get {
                return this.invoice_SatelliteProvider_Perfect_10_FulfillmentField;
            }
            set {
                this.invoice_SatelliteProvider_Perfect_10_FulfillmentField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Qwest {
            get {
                return this.invoice_SatelliteProvider_QwestField;
            }
            set {
                this.invoice_SatelliteProvider_QwestField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Qwest_Wireless {
            get {
                return this.invoice_SatelliteProvider_Qwest_WirelessField;
            }
            set {
                this.invoice_SatelliteProvider_Qwest_WirelessField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_SIRIUS {
            get {
                return this.invoice_SatelliteProvider_SIRIUSField;
            }
            set {
                this.invoice_SatelliteProvider_SIRIUSField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Sky_Angel {
            get {
                return this.invoice_SatelliteProvider_Sky_AngelField;
            }
            set {
                this.invoice_SatelliteProvider_Sky_AngelField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Sprint {
            get {
                return this.invoice_SatelliteProvider_SprintField;
            }
            set {
                this.invoice_SatelliteProvider_SprintField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_SunCom {
            get {
                return this.invoice_SatelliteProvider_SunComField;
            }
            set {
                this.invoice_SatelliteProvider_SunComField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_TMobile {
            get {
                return this.invoice_SatelliteProvider_TMobileField;
            }
            set {
                this.invoice_SatelliteProvider_TMobileField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_US_DTV {
            get {
                return this.invoice_SatelliteProvider_US_DTVField;
            }
            set {
                this.invoice_SatelliteProvider_US_DTVField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Verizon {
            get {
                return this.invoice_SatelliteProvider_VerizonField;
            }
            set {
                this.invoice_SatelliteProvider_VerizonField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_Vonage {
            get {
                return this.invoice_SatelliteProvider_VonageField;
            }
            set {
                this.invoice_SatelliteProvider_VonageField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_WildBlue {
            get {
                return this.invoice_SatelliteProvider_WildBlueField;
            }
            set {
                this.invoice_SatelliteProvider_WildBlueField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_WildBlue_Fulfillment {
            get {
                return this.invoice_SatelliteProvider_WildBlue_FulfillmentField;
            }
            set {
                this.invoice_SatelliteProvider_WildBlue_FulfillmentField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_SatelliteProvider_XM_Radio {
            get {
                return this.invoice_SatelliteProvider_XM_RadioField;
            }
            set {
                this.invoice_SatelliteProvider_XM_RadioField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Status_Pending {
            get {
                return this.invoice_Status_PendingField;
            }
            set {
                this.invoice_Status_PendingField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Status_Completed {
            get {
                return this.invoice_Status_CompletedField;
            }
            set {
                this.invoice_Status_CompletedField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Status_Cancelled {
            get {
                return this.invoice_Status_CancelledField;
            }
            set {
                this.invoice_Status_CancelledField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Status_NotScheduled {
            get {
                return this.invoice_Status_NotScheduledField;
            }
            set {
                this.invoice_Status_NotScheduledField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Status_Chargeback {
            get {
                return this.invoice_Status_ChargebackField;
            }
            set {
                this.invoice_Status_ChargebackField = value;
            }
        }
        
        /// <remarks/>
        public string Appointment_Results_Open {
            get {
                return this.appointment_Results_OpenField;
            }
            set {
                this.appointment_Results_OpenField = value;
            }
        }
        
        /// <remarks/>
        public string Appointment_Results_Rescheduled {
            get {
                return this.appointment_Results_RescheduledField;
            }
            set {
                this.appointment_Results_RescheduledField = value;
            }
        }
        
        /// <remarks/>
        public string Appointment_Results_Completed {
            get {
                return this.appointment_Results_CompletedField;
            }
            set {
                this.appointment_Results_CompletedField = value;
            }
        }
        
        /// <remarks/>
        public string Appointment_Results_Cancelled {
            get {
                return this.appointment_Results_CancelledField;
            }
            set {
                this.appointment_Results_CancelledField = value;
            }
        }
        
        /// <remarks/>
        public string Appointment_Results_Closed {
            get {
                return this.appointment_Results_ClosedField;
            }
            set {
                this.appointment_Results_ClosedField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCard_Type_Visa {
            get {
                return this.creditCard_Type_VisaField;
            }
            set {
                this.creditCard_Type_VisaField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCard_Type_Mastercard {
            get {
                return this.creditCard_Type_MastercardField;
            }
            set {
                this.creditCard_Type_MastercardField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCard_Type_AmericanExpress {
            get {
                return this.creditCard_Type_AmericanExpressField;
            }
            set {
                this.creditCard_Type_AmericanExpressField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCard_Type_Discover {
            get {
                return this.creditCard_Type_DiscoverField;
            }
            set {
                this.creditCard_Type_DiscoverField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Accounting {
            get {
                return this.note_Type_AccountingField;
            }
            set {
                this.note_Type_AccountingField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Ticket {
            get {
                return this.note_Type_TicketField;
            }
            set {
                this.note_Type_TicketField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Complaint {
            get {
                return this.note_Type_ComplaintField;
            }
            set {
                this.note_Type_ComplaintField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Follow_up_2 {
            get {
                return this.note_Type_Follow_up_2Field;
            }
            set {
                this.note_Type_Follow_up_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Processing {
            get {
                return this.note_Type_ProcessingField;
            }
            set {
                this.note_Type_ProcessingField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Follow_up_3 {
            get {
                return this.note_Type_Follow_up_3Field;
            }
            set {
                this.note_Type_Follow_up_3Field = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Reconciliation {
            get {
                return this.note_Type_ReconciliationField;
            }
            set {
                this.note_Type_ReconciliationField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Lead_Flow {
            get {
                return this.note_Type_Lead_FlowField;
            }
            set {
                this.note_Type_Lead_FlowField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Manual_Update {
            get {
                return this.note_Type_Manual_UpdateField;
            }
            set {
                this.note_Type_Manual_UpdateField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Route {
            get {
                return this.note_Type_RouteField;
            }
            set {
                this.note_Type_RouteField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Pre_Call {
            get {
                return this.note_Type_Pre_CallField;
            }
            set {
                this.note_Type_Pre_CallField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Follow_up_1 {
            get {
                return this.note_Type_Follow_up_1Field;
            }
            set {
                this.note_Type_Follow_up_1Field = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Status {
            get {
                return this.note_Type_StatusField;
            }
            set {
                this.note_Type_StatusField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Trouble_Call {
            get {
                return this.note_Type_Trouble_CallField;
            }
            set {
                this.note_Type_Trouble_CallField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Callback {
            get {
                return this.note_Type_CallbackField;
            }
            set {
                this.note_Type_CallbackField = value;
            }
        }
        
        /// <remarks/>
        public string Note_Type_Billing {
            get {
                return this.note_Type_BillingField;
            }
            set {
                this.note_Type_BillingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getExeptionReportObjectCompletedEventHandler(object sender, getExeptionReportObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExeptionReportObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExeptionReportObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionReport Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionReport)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidateEntityCompletedEventHandler(object sender, ValidateEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getTypesCompletedEventHandler(object sender, getTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Types Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Types)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAccountIDFromLeadIDCompletedEventHandler(object sender, GetAccountIDFromLeadIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountIDFromLeadIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountIDFromLeadIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAccountIDFromPhoneCompletedEventHandler(object sender, GetAccountIDFromPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountIDFromPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountIDFromPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetLeadIDFromPhoneCompletedEventHandler(object sender, GetLeadIDFromPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeadIDFromPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeadIDFromPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CreateEntityCompletedEventHandler(object sender, CreateEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UploadProviderDocumentCompletedEventHandler(object sender, UploadProviderDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadProviderDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadProviderDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateEntityCompletedEventHandler(object sender, UpdateEntityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCampaignNameFromLeadIDCompletedEventHandler(object sender, getCampaignNameFromLeadIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCampaignNameFromLeadIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCampaignNameFromLeadIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCampaignNameFromAccountIDCompletedEventHandler(object sender, getCampaignNameFromAccountIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCampaignNameFromAccountIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCampaignNameFromAccountIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getProviderFromLeadIDCompletedEventHandler(object sender, getProviderFromLeadIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProviderFromLeadIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProviderFromLeadIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getProviderFromAccountIDCompletedEventHandler(object sender, getProviderFromAccountIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProviderFromAccountIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProviderFromAccountIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591