using System;

namespace DataReef.TM.Models
{
    public class NewMexicoData
    {
        public int id { get; set; }
        public string DBUSA_Household_ID { get; set; }
        public string DBUSA_Individual_ID { get; set; }
        public string Location_ID { get; set; }
        public string Full_Name { get; set; }
        public string Name_Prefix { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Suffix { get; set; }
        public string Gender { get; set; }
        public string Date_Of_Birth_Year { get; set; }
        public string Date_Of_Birth_Month { get; set; }
        public string Age { get; set; }
        public string Age_Code_Description { get; set; }
        public string Ethnic_Code { get; set; }
        public string Ethnic_Group { get; set; }
        public string Religious_Affiliation { get; set; }
        public string Language_Preference { get; set; }
        public string Hispanic_Country_Of_Origin { get; set; }
        public string Assimilation_Code { get; set; }
        public string Education_Individual { get; set; }
        public string Occupation_Individual { get; set; }
        public string Occupation_Individual_Range { get; set; }
        public string Political_Party_Individual { get; set; }
        public string Political_Ideology { get; set; }
        public string Voter_ID { get; set; }
        public string Veteran_Individual { get; set; }
        public string Mail_Score_Code { get; set; }
        public string Standardized_Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ZIP_Plus4 { get; set; }
        public string Carrier_Route { get; set; }
        public string Delivery_Point { get; set; }
        public string Delivery_Point_Check_Digit { get; set; }
        public string Address_Street_Number { get; set; }
        public string Address_Street_Pre { get; set; }
        public string Address_Street_Name { get; set; }
        public string Address_Street_Suffix { get; set; }
        public string Address_Street_Post { get; set; }
        public string Address_Suite_Name { get; set; }
        public string Address_Suite_Number { get; set; }
        public string Line_Of_Travel { get; set; }
        public string GeoCode_Match_Level { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Time_Zone_Code { get; set; }
        public string Time_Zone_Description { get; set; }
        public string Census_Tract { get; set; }
        public string Census_Block { get; set; }
        public string County_Code { get; set; }
        public string County_Name { get; set; }
        public string FIPS_Code { get; set; }
        public string CBSA_Code { get; set; }
        public string CBSA_Description { get; set; }
        public string Walk_Sequence { get; set; }
        public string District_Congressional { get; set; }
        public string District_State_Senate { get; set; }
        public string District_State_House { get; set; }
        public string District_State_Legislative { get; set; }
        public string DMA_Code { get; set; }
        public string DMA_Zone { get; set; }
        public string Email_Present { get; set; }
        public string Email { get; set; }
        public string Email_02 { get; set; }
        public string Email_03 { get; set; }
        public string Email_04 { get; set; }
        public string Email_05 { get; set; }
        public string Area_Code { get; set; }
        public string Phone { get; set; }
        public string DNC { get; set; }
        public string Scrubbed_Phoneable { get; set; }
        public string Area_Code_Cell_Phone { get; set; }
        public string Cell_Phone { get; set; }
        public string Dwelling_Type { get; set; }
        public string Home_Owner_Renter { get; set; }
        public string Length_Of_Residence { get; set; }
        public string Length_of_Residence_Code { get; set; }
        public string Length_Of_Residence_Description { get; set; }
        public string Recently_Moved_Flag { get; set; }
        public string Recently_Moved_Year { get; set; }
        public string Recently_Moved_Month { get; set; }
        public string Household_Size { get; set; }
        public string Household_Rank { get; set; }
        public string Number_Of_Adults { get; set; }
        public string Young_Adult_In_Household { get; set; }
        public string Senior_Adult_In_Household { get; set; }
        public string Generations_In_Household { get; set; }
        public string Marital_Status { get; set; }
        public string Recent_Divorce { get; set; }
        public string Single_Parent { get; set; }
        public string Children_Present { get; set; }
        public string Number_Children { get; set; }
        public string Childrens_Age_00_02 { get; set; }
        public string Childrens_Age_00_02_Male { get; set; }
        public string Childrens_Age_00_02_Female { get; set; }
        public string Childrens_Age_00_02_Unknown { get; set; }
        public string Childrens_Age_03_05 { get; set; }
        public string Childrens_Age_03_05_Male { get; set; }
        public string Childrens_Age_03_05_Female { get; set; }
        public string Childrens_Age_03_05_Unknown { get; set; }
        public string Childrens_Age_06_10 { get; set; }
        public string Childrens_Age_06_10_Male { get; set; }
        public string Childrens_Age_06_10_Female { get; set; }
        public string Childrens_Age_06_10_Unknown { get; set; }
        public string Childrens_Age_11_15 { get; set; }
        public string Childrens_Age_11_15_Male { get; set; }
        public string Childrens_Age_11_15_Female { get; set; }
        public string Childrens_Age_11_15_Unknown { get; set; }
        public string Childrens_Age_16_17 { get; set; }
        public string Childrens_Age_16_17_Male { get; set; }
        public string Childrens_Age_16_17_Female { get; set; }
        public string Childrens_Age_16_17_Unknown { get; set; }
        public string Child_Near_High_School_Graduation { get; set; }
        public string College_Graduate { get; set; }
        public string Christian_Families { get; set; }
        public string Business_Owner { get; set; }
        public string SOHO { get; set; }
        public string Working_Woman { get; set; }
        public string Veteran_Present_In_Household { get; set; }
        public string Credit_Card_User { get; set; }
        public string Mail_Order_Donor { get; set; }
        public string Mail_Order_Buyer { get; set; }
        public string Mail_Order_Responder { get; set; }
        public string TV_Satellite_Dish { get; set; }
        public string Pet_Owner { get; set; }
        public string Cat_Owner { get; set; }
        public string Dog_Owner { get; set; }
        public string Other_Pet_Owner { get; set; }
        public string New_Teen_Driver { get; set; }
        public string New_Teen_Driver_Gender { get; set; }
        public string Boat_Owner { get; set; }
        public string Truck_Owner { get; set; }
        public string Motorcycle_Owner { get; set; }
        public string RV_Owner { get; set; }
        public string Auto_Buy_New { get; set; }
        public string Auto_Buy_Used { get; set; }
        public string Auto_Buy_Used_5_Months_Or_Less { get; set; }
        public string Auto_Buy_Used_6_Months_Or_More { get; set; }
        public string Median_HseHld_Income { get; set; }
        public string Median_HseHld_Income_Code { get; set; }
        public string Median_HseHld_Income_Description { get; set; }
        public string Income { get; set; }
        public string Income_Code { get; set; }
        public string Income_Description { get; set; }
        public string NetWorth { get; set; }
        public string NetWorth_Code { get; set; }
        public string NetWorth_Description { get; set; }
        public string Millionaire { get; set; }
        public string Unsecured_Credit_Capacity { get; set; }
        public string Unsecured_Credit_Capacity_Code { get; set; }
        public string Unsecured_Credit_Capacity_Description { get; set; }
        public string Discretionary_Income { get; set; }
        public string Discretionary_Income_Code { get; set; }
        public string Discretionary_Income_Description { get; set; }
        public string Donor_Capacity { get; set; }
        public string Donor_Capacity_Code { get; set; }
        public string Donor_Capacity_Description { get; set; }
        public string Investment_Properties_Owned { get; set; }
        public string Estimated_Area_Credit_Rating { get; set; }
        public string CRA_Income_Classification_Code { get; set; }
        public string Credit_Range_New_Credit { get; set; }
        public string Lines_Of_Credit { get; set; }
        public string Home_Property_Type { get; set; }
        public string Home_Property_Type_Detail { get; set; }
        public string Home_Value { get; set; }
        public string Home_Value_Code { get; set; }
        public string Home_Value_Description { get; set; }
        public string Median_Home_Value { get; set; }
        public string Median_Home_Value_Code { get; set; }
        public string Median_Home_Value_Description { get; set; }
        public string Home_Built_Year { get; set; }
        public string Home_Built_Year_Code { get; set; }
        public string Home_Built_Year_Description { get; set; }
        public string Home_Square_Footage { get; set; }
        public string Home_Square_Footage_Range { get; set; }
        public string Land_Square_Footage { get; set; }
        public string Number_Of_Bedrooms { get; set; }
        public string Number_Of_Bathrooms { get; set; }
        public string Home_Air_Conditioning { get; set; }
        public string Home_Swimming_Pool { get; set; }
        public string Home_Sewer { get; set; }
        public string Home_Water { get; set; }
        public string Recent_Home_Buyer { get; set; }
        public string Recent_Mortgage_Borrower { get; set; }
        public string New_Home_Owner_Flag { get; set; }
        public string Most_Recent_Home_Purchase_Date_Flag { get; set; }
        public string Home_Purchase_Date { get; set; }
        public string Home_Purchase_Year { get; set; }
        public string Home_Purchase_Amount { get; set; }
        public string Home_Assessed_Value { get; set; }
        public string Home_Total_Loan { get; set; }
        public string Home_Loan_Date_1_Year { get; set; }
        public string Home_Loan_Date_1_Month { get; set; }
        public string Home_Loan_Date_2_Year { get; set; }
        public string Home_Loan_Date_2_Month { get; set; }
        public string Home_Loan_Date_3_Year { get; set; }
        public string Home_Loan_Date_3_Month { get; set; }
        public string Home_Loan_Amount_1 { get; set; }
        public string Home_Loan_Amount_2 { get; set; }
        public string Home_Loan_Amount_3 { get; set; }
        public string Home_Loan_Type_1 { get; set; }
        public string Home_Loan_Type_2 { get; set; }
        public string Home_Loan_Type_3 { get; set; }
        public string Home_Loan_Interest_Rate_1 { get; set; }
        public string Home_Loan_Interest_Rate_2 { get; set; }
        public string Home_Loan_Interest_Rate_3 { get; set; }
        public string Home_Loan_Interest_Rate_Type_1 { get; set; }
        public string Home_Loan_Interest_Rate_Type_2 { get; set; }
        public string Home_Loan_Interest_Rate_Type_3 { get; set; }
        public string Home_Loan_Transaction_Type_1 { get; set; }
        public string Home_Loan_Transaction_Type_2 { get; set; }
        public string Home_Loan_Transaction_Type_3 { get; set; }
        public string Home_Loan_Lender_Name_1 { get; set; }
        public string Home_Loan_Lender_Name_2 { get; set; }
        public string Home_Loan_Lender_Name_3 { get; set; }
        public string Home_Loan_To_Value_Code { get; set; }
        public string Home_Equity_Available_Code { get; set; }
        public string Home_Equity_Available_Description { get; set; }
        public string Donor_Charitable { get; set; }
        public string Donor_Animal_Welfare { get; set; }
        public string Donor_Arts_Cultural { get; set; }
        public string Donor_Childrens { get; set; }
        public string Donor_Environment_Wildlife { get; set; }
        public string Donor_Health { get; set; }
        public string Donor_International_Aid { get; set; }
        public string Donor_Political { get; set; }
        public string Donor_Political_Conservative { get; set; }
        public string Donor_Political_Liberal { get; set; }
        public string Donor_Religious { get; set; }
        public string Donor_Veterans { get; set; }
        public string CC_American_Express { get; set; }
        public string CC_American_Express_Gold_Platinum { get; set; }
        public string CC_Discover { get; set; }
        public string CC_Visa { get; set; }
        public string CC_Mastercard { get; set; }
        public string CC_Bank { get; set; }
        public string CC_Gas_Dept_Retail { get; set; }
        public string CC_Travel_Entertainment { get; set; }
        public string CC_Unknown { get; set; }
        public string CC_Gold_Platinum { get; set; }
        public string CC_Premium { get; set; }
        public string CC_Upscale_Dept { get; set; }
        public string CC_New_Issue { get; set; }
        public string Home_Living { get; set; }
        public string DIY_Living { get; set; }
        public string Sporty_Living { get; set; }
        public string Upscale_Living { get; set; }
        public string Cultural_Artistic_Living { get; set; }
        public string Highbrow { get; set; }
        public string Common_Living { get; set; }
        public string Professional_Living { get; set; }
        public string Broader_Living { get; set; }
        public string Arts { get; set; }
        public string Theater_Performing_Arts { get; set; }
        public string Food_Wines { get; set; }
        public string Foods_Natural { get; set; }
        public string Cooking_General { get; set; }
        public string Cooking_Gourmet { get; set; }
        public string Aviation { get; set; }
        public string Auto_Work { get; set; }
        public string Automotive_Buff { get; set; }
        public string Beauty_Cosmetics { get; set; }
        public string Career { get; set; }
        public string Career_Improvement { get; set; }
        public string Parenting { get; set; }
        public string Childrens_Interests { get; set; }
        public string Grandchildren { get; set; }
        public string Community_Charities { get; set; }
        public string Religious_Inspirational { get; set; }
        public string Crafts { get; set; }
        public string Photography { get; set; }
        public string Sewing_Knitting_Needlework { get; set; }
        public string Collector_Avid { get; set; }
        public string Collectibles_Grouping { get; set; }
        public string Collectibles_General { get; set; }
        public string Collectibles_Stamps { get; set; }
        public string Collectibles_Coins { get; set; }
        public string Collectibles_Arts { get; set; }
        public string Collectibles_Antiques { get; set; }
        public string Collectibles_Sports_Memorabilia { get; set; }
        public string Education_Online { get; set; }
        public string Exercise_Aerobic { get; set; }
        public string Exercise_Running_Jogging { get; set; }
        public string Exercise_Walking { get; set; }
        public string High_Tech_General { get; set; }
        public string Games_Computer_Games { get; set; }
        public string Games_Video_Games { get; set; }
        public string Games_Board_Puzzles { get; set; }
        public string Gaming_Casino { get; set; }
        public string Consumer_Electronics { get; set; }
        public string Environmental_Issues { get; set; }
        public string Gardening { get; set; }
        public string Home_Furnishings_Decorating { get; set; }
        public string House_Plant { get; set; }
        public string Home_Improvement_Grouping { get; set; }
        public string Home_Improvement { get; set; }
        public string Home_Improvement_DIY { get; set; }
        public string Health_Medical { get; set; }
        public string Dieting_Weight_Loss { get; set; }
        public string Self_Improvement { get; set; }
        public string Investments_Grouping { get; set; }
        public string Investments_Foreign { get; set; }
        public string Investments_Personal { get; set; }
        public string Investments_Real_Estate { get; set; }
        public string Investments_Stocks_Bonds { get; set; }
        public string Money_Seekers { get; set; }
        public string Sweepstakes_Contests { get; set; }
        public string Music_Home_Stereo { get; set; }
        public string Music_Player { get; set; }
        public string Music_Collector { get; set; }
        public string Music_Listener { get; set; }
        public string Movie_Grouping { get; set; }
        public string Movie_Music_General { get; set; }
        public string Movie_Collector { get; set; }
        public string Reading_General { get; set; }
        public string Reading_Audio_Books { get; set; }
        public string Reading_Magazines { get; set; }
        public string Reading_Religious_Inspirational { get; set; }
        public string Reading_Science_Fiction { get; set; }
        public string Reading_Financial_Newsletter_Subscribers { get; set; }
        public string Current_Affairs_Politics { get; set; }
        public string History_Military { get; set; }
        public string Outdoor_Grouping { get; set; }
        public string Outdoor_Enthusiast_General { get; set; }
        public string Outdoor_Fishing { get; set; }
        public string Outdoor_Boating_Sailing { get; set; }
        public string Outdoor_Camping_Hiking { get; set; }
        public string Outdoor_Hunting_Shooting { get; set; }
        public string Outdoor_Scuba_Diving { get; set; }
        public string Spectator_Sports_Grouping { get; set; }
        public string Spectator_Sports_General { get; set; }
        public string Spectator_Sports_Baseball { get; set; }
        public string Spectator_Sports_Basketball { get; set; }
        public string Spectator_Sports_Football { get; set; }
        public string Spectator_Sports_Hockey { get; set; }
        public string Spectator_Sports_Racing { get; set; }
        public string Spectator_Sports_Soccer { get; set; }
        public string Spectator_Sports_TV_Sports { get; set; }
        public string Spectator_NASCAR { get; set; }
        public string Smoking_Tobacco { get; set; }
        public string Sports_Grouping { get; set; }
        public string Sports_Equestrian { get; set; }
        public string Sports_Golf { get; set; }
        public string Sports_Motorcycling { get; set; }
        public string Sports_Skiing { get; set; }
        public string Sports_Tennis { get; set; }
        public string Travel_Grouping { get; set; }
        public string Travel_Cruises { get; set; }
        public string Travel_Domestic { get; set; }
        public string Travel_International { get; set; }
        public string Travel_RV { get; set; }
        public string Science_Space { get; set; }
        public string Woodworking { get; set; }
        public string Buyer_Books { get; set; }
        public string Buyer_Crafts_Hobbies { get; set; }
        public string Buyer_Gardening_Farming { get; set; }
        public string Buyer_Jewelry { get; set; }
        public string Buyer_Luggage { get; set; }
        public string Buyer_Online { get; set; }
        public string Buyer_Membership_Club { get; set; }
        public string Buyer_Merchandise_Male { get; set; }
        public string Buyer_Merchandise_Female { get; set; }
        public string Buyer_Health_Beauty { get; set; }
        public string Buyer_Childrens_Babycare { get; set; }
        public string Buyer_Childrens_Learning_Toys { get; set; }
        public string Buyer_Childrens_Back_To_School { get; set; }
        public string Apparel_Childrens { get; set; }
        public string Apparel_Infant_Toddlers { get; set; }
        public string Apparel_Womens { get; set; }
        public string Apparel_Womens_Petite { get; set; }
        public string Apparel_Womens_Plus_Size { get; set; }
        public string Apparel_Womens_Young { get; set; }
        public string Apparel_Mens { get; set; }
        public string Apparel_Mens_Big_Tall { get; set; }
        public string Apparel_Mens_Young { get; set; }
        public string Auto_Parts_Accessories { get; set; }
        public string Military_Memorabilia_Weapons { get; set; }
        public string Musical_Instruments { get; set; }
        public string Photography_Video_Equipment { get; set; }
        public string Sports_Leisure { get; set; }
        public string Value_Hunter { get; set; }
        public string Last_Update_Date { get; set; }
        public string Source_Data { get; set; }
        public string Production_Date { get; set; }

    }
}
